## 生成随机图

In [1]:
import numpy as np
import time

In [2]:
#生成随机有向图图
#两个参数，节点个数，边的比例（稀疏矩阵默认0.3）
def getRandomDirectedGraph(vertex, ratio = 0.3):
    #n方的0矩阵
    graph = np.matrix(np.zeros([vertex, vertex]))
    
    #随机添加边
    #稀疏矩阵，1的数量占不超过30%
    #且边取整数
    edge_num = int(ratio * pow(vertex, 2))
    
    while edge_num > 0:
        row = np.random.choice(vertex)
        col = np.random.choice(vertex)
        graph[row, col] = 1
        edge_num -= 1
        
    #节点不能自连，故对角不能为1
    Z = np.matrix(np.zeros([vertex, vertex]))
    graph = graph + Z - np.diag(np.diag(graph))
    
    return graph

In [3]:
#生成随机无向图图
#两个参数，节点个数，边的比例（稀疏矩阵默认0.3）
def getRandomUndirectedGraph(vertex, ratio = 0.3):
    #n方的0矩阵
    graph = np.matrix(np.zeros([vertex, vertex]))
    
    #随机添加边
    #稀疏矩阵，1的数量占不超过30%
    #且边取整数
    edge_num = int(ratio * pow(vertex, 2))
    
    while edge_num > 0:
        row = np.random.choice(vertex)
        col = np.random.choice(vertex)
        graph[row, col] = 1
        graph[col, row] = 1
        edge_num -= 2
        
    #节点不能自连，故对角不能为1
    Z = np.matrix(np.zeros([vertex, vertex]))
    graph = graph + Z - np.diag(np.diag(graph))
    
    return graph

## 利用生成的随机图测试三种算法

In [32]:
vertex = 2000
graph = getRandomDirectedGraph(vertex)
graph

matrix([[0., 1., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.],
        [1., 1., 0., ..., 0., 0., 0.]])

### 1. 原生迭代simrank

In [5]:
from algorithms import naive_simrank

In [17]:
naive_simrank.simrank(graph, vertex)

RunTime： 123.1159892


matrix([[1.        , 0.04416729, 0.06787639, ..., 0.05146197, 0.04664046,
         0.04191698],
        [0.04416729, 1.        , 0.04698447, ..., 0.04723448, 0.0522821 ,
         0.05917532],
        [0.06787639, 0.04698447, 1.        , ..., 0.05271231, 0.05017836,
         0.05339487],
        ...,
        [0.05146197, 0.04723448, 0.05271231, ..., 1.        , 0.05880206,
         0.05255817],
        [0.04664046, 0.0522821 , 0.05017836, ..., 0.05880206, 1.        ,
         0.0535808 ],
        [0.04191698, 0.05917532, 0.05339487, ..., 0.05255817, 0.0535808 ,
         1.        ]])

### 2. 优化后的simrank

In [7]:
from algorithms import optimize_simrank

In [24]:
optimize_simrank.simrank(graph, vertex)

RunTime： 661.4754402000001


matrix([[1.        , 0.01270157, 0.01311934, ..., 0.01340536, 0.0132655 ,
         0.01317736],
        [0.01270157, 1.        , 0.01474516, ..., 0.01180661, 0.01208208,
         0.01155274],
        [0.01311934, 0.01474516, 1.        , ..., 0.01336478, 0.01268938,
         0.01413122],
        ...,
        [0.01340536, 0.01180661, 0.01336478, ..., 1.        , 0.01259271,
         0.01419013],
        [0.0132655 , 0.01208208, 0.01268938, ..., 0.01259271, 1.        ,
         0.01471204],
        [0.01317736, 0.01155274, 0.01413122, ..., 0.01419013, 0.01471204,
         1.        ]])

### 3. 矩阵simrank

In [9]:
from algorithms import matrix_simrank

In [33]:
matrix_simrank.simrank(graph, vertex)

RunTime： 137.9360842000001


matrix([[1.        , 0.00130808, 0.0013914 , ..., 0.00135374, 0.00134999,
         0.00135456],
        [0.00130808, 1.        , 0.00133378, ..., 0.00132234, 0.0013493 ,
         0.0013578 ],
        [0.0013914 , 0.00133378, 1.        , ..., 0.00137231, 0.00135023,
         0.00134034],
        ...,
        [0.00135374, 0.00132234, 0.00137231, ..., 1.        , 0.00138288,
         0.00135476],
        [0.00134999, 0.0013493 , 0.00135023, ..., 0.00138288, 1.        ,
         0.00137196],
        [0.00135456, 0.0013578 , 0.00134034, ..., 0.00135476, 0.00137196,
         1.        ]])